import React, {useEffect, useMemo, useRef, useState} from 'react';
import { createRoot } from 'react-dom/client';
import { AnimatePresence, motion, useReducedMotion, useScroll, useSpring, useTransform } from 'framer-motion';
import { ArrowDownRight, ArrowLeft, ArrowRight, Check, Menu, X } from 'lucide-react';
import './styles.css';
import recipeImages from './recipeImages.js';

const countries = [
  {code:'FI', n:'01', lat:'61°N', local:'Suomi', slug:'lohikeitto', category:'fish', color:'#d8e5e7', accent:'#5d7f86', image:recipeImages['lohikeitto']},
  {code:'FR', n:'02', lat:'43°N', local:'France', slug:'ratatouille', category:'natural-vegan', color:'#ead8d0', accent:'#8a5f52', image:recipeImages['ratatouille']},
  {code:'IE', n:'03', lat:'53°N', local:'Éire', slug:'irish-stew', category:'meat', color:'#dfe6d4', accent:'#687653', image:recipeImages['irish-stew']},
  {code:'NL', n:'04', lat:'52°N', local:'Nederland', slug:'poffertjes', category:'vegetarian', color:'#f1dfc6', accent:'#a56f37', image:recipeImages['poffertjes']},
  {code:'PT', n:'05', lat:'38°N', local:'Portugal', slug:'bacalhau-a-bras', category:'fish', color:'#d9e0d1', accent:'#748066', image:recipeImages['bacalhau-a-bras']},
  {code:'ES', n:'06', lat:'40°N', local:'España', slug:'tortilla-de-patatas', category:'vegetarian', color:'#eed7b1', accent:'#9c6a2d', image:recipeImages['tortilla-de-patatas']},
];

const COUNTRY_NAMES = {
  DE:{FI:'Finnland',FR:'Frankreich',IE:'Irland',NL:'Niederlande',PT:'Portugal',ES:'Spanien'},
  EN:{FI:'Finland',FR:'France',IE:'Ireland',NL:'Netherlands',PT:'Portugal',ES:'Spain'},
  PT:{FI:'Finlândia',FR:'França',IE:'Irlanda',NL:'Países Baixos',PT:'Portugal',ES:'Espanha'},
};

const UI = {
 DE:{
  languageAria:'Sprache wählen',menu:'Menü',home:'Startseite',allRecipes:'Alle Rezepte',aboutProject:'Über das Projekt',closeMenu:'Menü schließen',
  europe:'Europa',heroPlate:'auf dem Teller.',heroLead:'Sechs Länder. Sechs traditionelle Gerichte. Sechs vegane Interpretationen.',heroSub:'Ein kulinarisches Erasmus+-Projekt des Pictorius Berufskollegs Coesfeld.',
  discoverCountries:'Länder entdecken',discoverRecipes:'Rezepte entdecken',scrollDrag:'Scroll / Ziehen',
  countriesKicker:'Die Länder',chooseCountry:'Wähle ein Land.',countriesDesc:'Von 61° Nord bis 38° Nord – jedes Land bringt ein traditionelles Gericht und seine vegane Interpretation mit.',
  recipesKicker:'Die Rezepte',allDishes:'Alle Gerichte',dishes:'Gerichte',openRecipe:'Rezept öffnen',naturalVegan:'Von Natur aus vegan',
  filterAll:'Alle',filterVegan:'Vegane Varianten',filterNatural:'Von Natur aus vegan',filterVegetarian:'Vegetarisch',filterFish:'Mit Fisch',filterMeat:'Mit Fleisch',
  projectKicker:'Über das Projekt',projectTitle:'Ein Projekt zwischen Gestaltung, Europa und Küche.',projectDesc:'Im Rahmen von Erasmus+ erkunden die Schülerinnen und Schüler des Pictorius Berufskollegs Coesfeld traditionelle Gerichte aus sechs europäischen Ländern – und entwickeln für jedes eine vegane Interpretation. Jede Holzkarte trägt einen QR-Code, der direkt zum Rezept führt.',
  projectImage:'Projektarbeit',stepWood:'Holzkarte',stepWoodSub:'Gestaltet und gefräst im Berufskolleg',stepQr:'QR scannen',stepQrSub:'Direkter Link zum jeweiligen Rezept',stepRecipe:'Rezept öffnet sich',stepRecipeSub:'Traditionell und vegan auf einer Seite',
  statsTitle:'Ein Erasmus+-Projekt',countries:'Länder',traditionalDishes:'traditionelle Gerichte',veganInterpretations:'vegane Interpretationen',
  footerProject:'Ein Erasmus+-Projekt',backToTop:'Nach oben ↑',
  recipeVariant:'Rezeptvariante',chooseVariant:'Rezeptvariante wählen',original:'Original',vegan:'Vegan',veganVariant:'Vegane Variante',
  portions:'Portionen',time:'Zeit',type:'Art',ingredients:'Zutaten',ready:'bereit',preparation:'Zubereitung',of:'von',stepsDone:'Schritten erledigt',step:'Schritt',open:'Öffnen',opened:'Offen',markOpen:'Als offen markieren',stepDone:'Schritt erledigt',prep:'Vorbereitung',serve:'Servieren',previousDish:'Vorheriges Gericht',nextDish:'Nächstes Gericht',viewAllRecipes:'Alle Rezepte ansehen',back:'Zurück',
  easy:'Einfach',medium:'Mittel',naturalType:'Von Natur aus vegan',
 },
 EN:{
  languageAria:'Choose language',menu:'Menu',home:'Home',allRecipes:'All recipes',aboutProject:'About the project',closeMenu:'Close menu',
  europe:'Europe',heroPlate:'on the plate.',heroLead:'Six countries. Six traditional dishes. Six vegan interpretations.',heroSub:'A culinary Erasmus+ project by Pictorius Berufskolleg Coesfeld.',
  discoverCountries:'Discover countries',discoverRecipes:'Discover recipes',scrollDrag:'Scroll / Drag',
  countriesKicker:'The countries',chooseCountry:'Choose a country.',countriesDesc:'From 61° north to 38° north – every country contributes one traditional dish and its vegan interpretation.',
  recipesKicker:'The recipes',allDishes:'All dishes',dishes:'Dishes',openRecipe:'Open recipe',naturalVegan:'Naturally vegan',
  filterAll:'All',filterVegan:'Vegan versions',filterNatural:'Naturally vegan',filterVegetarian:'Vegetarian',filterFish:'With fish',filterMeat:'With meat',
  projectKicker:'About the project',projectTitle:'A project connecting design, Europe and food.',projectDesc:'As part of Erasmus+, students at Pictorius Berufskolleg Coesfeld explore traditional dishes from six European countries and develop a vegan interpretation of each one. Every wooden card carries a QR code that links directly to the recipe.',
  projectImage:'Project work',stepWood:'Wooden card',stepWoodSub:'Designed and milled at the vocational college',stepQr:'Scan QR code',stepQrSub:'Direct link to the corresponding recipe',stepRecipe:'Recipe opens',stepRecipeSub:'Traditional and vegan on one page',
  statsTitle:'An Erasmus+ project',countries:'Countries',traditionalDishes:'traditional dishes',veganInterpretations:'vegan interpretations',
  footerProject:'An Erasmus+ project',backToTop:'Back to top ↑',
  recipeVariant:'Recipe version',chooseVariant:'Choose recipe version',original:'Original',vegan:'Vegan',veganVariant:'Vegan version',
  portions:'Servings',time:'Time',type:'Type',ingredients:'Ingredients',ready:'ready',preparation:'Method',of:'of',stepsDone:'steps completed',step:'Step',open:'Open',opened:'Open',markOpen:'Mark as not done',stepDone:'Step completed',prep:'Preparation',serve:'To serve',previousDish:'Previous dish',nextDish:'Next dish',viewAllRecipes:'View all recipes',back:'Back',
  easy:'Easy',medium:'Medium',naturalType:'Naturally vegan',
 },
 PT:{
  languageAria:'Escolher idioma',menu:'Menu',home:'Início',allRecipes:'Todas as receitas',aboutProject:'Sobre o projeto',closeMenu:'Fechar menu',
  europe:'Europa',heroPlate:'no prato.',heroLead:'Seis países. Seis pratos tradicionais. Seis interpretações veganas.',heroSub:'Um projeto culinário Erasmus+ do Pictorius Berufskolleg Coesfeld.',
  discoverCountries:'Descobrir países',discoverRecipes:'Descobrir receitas',scrollDrag:'Deslizar / Arrastar',
  countriesKicker:'Os países',chooseCountry:'Escolha um país.',countriesDesc:'De 61° norte a 38° norte – cada país apresenta um prato tradicional e a sua interpretação vegana.',
  recipesKicker:'As receitas',allDishes:'Todos os pratos',dishes:'Pratos',openRecipe:'Abrir receita',naturalVegan:'Naturalmente vegano',
  filterAll:'Todos',filterVegan:'Versões veganas',filterNatural:'Naturalmente vegano',filterVegetarian:'Vegetariano',filterFish:'Com peixe',filterMeat:'Com carne',
  projectKicker:'Sobre o projeto',projectTitle:'Um projeto entre design, Europa e gastronomia.',projectDesc:'No âmbito do Erasmus+, os alunos do Pictorius Berufskolleg Coesfeld exploram pratos tradicionais de seis países europeus e desenvolvem uma interpretação vegana para cada um. Cada placa de madeira contém um código QR que leva diretamente à receita.',
  projectImage:'Trabalho do projeto',stepWood:'Placa de madeira',stepWoodSub:'Desenhada e fresada na escola profissional',stepQr:'Ler código QR',stepQrSub:'Ligação direta para a respetiva receita',stepRecipe:'A receita abre',stepRecipeSub:'Tradicional e vegana na mesma página',
  statsTitle:'Um projeto Erasmus+',countries:'Países',traditionalDishes:'pratos tradicionais',veganInterpretations:'interpretações veganas',
  footerProject:'Um projeto Erasmus+',backToTop:'Voltar ao topo ↑',
  recipeVariant:'Versão da receita',chooseVariant:'Escolher versão da receita',original:'Original',vegan:'Vegano',veganVariant:'Versão vegana',
  portions:'Porções',time:'Tempo',type:'Tipo',ingredients:'Ingredientes',ready:'prontos',preparation:'Preparação',of:'de',stepsDone:'passos concluídos',step:'Passo',open:'Abrir',opened:'Aberto',markOpen:'Marcar como não concluído',stepDone:'Passo concluído',prep:'Preparação prévia',serve:'Servir',previousDish:'Prato anterior',nextDish:'Próximo prato',viewAllRecipes:'Ver todas as receitas',back:'Voltar',
  easy:'Fácil',medium:'Médio',naturalType:'Naturalmente vegano',
 }
};

const RECIPES = {
 DE:{
  'lohikeitto':{title:'Lohikeitto',subtitle:'Finnische Lachssuppe',portions:'4 Portionen',time:'ca. 40 Minuten',typeKey:'easy',desc:'Lohikeitto ist eine traditionelle finnische Lachssuppe mit Kartoffeln, Lauch, Sahne und Dill. Das Zusammenspiel aus cremiger Brühe, mildem Lachs und frischem Dill macht sie besonders typisch für die nordische Küche.',ingredients:['400 g Lachsfilet ohne Haut','600 g festkochende Kartoffeln','200 g Karotten','1 großer Lauch','1 EL Butter','700 ml Fischfond oder milde Fischbrühe','200 ml Sahne','1 Lorbeerblatt','3 Pimentkörner','½ Bund frischer Dill','1–2 EL Zitronensaft','Salz','schwarzer oder weißer Pfeffer'],steps:['Kartoffeln schälen und in etwa 2 cm große Würfel schneiden. Karotten in Scheiben, den gewaschenen Lauch in dünne Ringe schneiden. Den Lachs auf Gräten kontrollieren und in etwa 2–3 cm große Würfel schneiden.','Butter in einem großen Topf bei mittlerer Hitze schmelzen. Den Lauch 3–4 Minuten sanft anschwitzen, dann Kartoffeln und Karotten dazugeben und kurz mit anschwitzen.','Fischfond, Lorbeerblatt und Piment hinzufügen, aufkochen und 12–15 Minuten bei mittlerer Hitze köcheln lassen, bis die Kartoffeln fast gar sind.','Sahne einrühren, die Lachswürfel vorsichtig hineingeben und 4–6 Minuten sanft ziehen lassen. Nicht kräftig weiterkochen.','Lorbeer und Piment entfernen. Gehackten Dill und Zitronensaft unterrühren und mit Salz und Pfeffer abschmecken.'],serve:'Sehr heiß servieren und mit frischem Dill bestreuen. Dunkles Roggenbrot passt besonders gut dazu.'},
  'ratatouille':{title:'Ratatouille',subtitle:'Provenzalisches Gemüsegericht',portions:'4 Portionen',time:'ca. 60–75 Minuten',typeKey:'naturalVegan',desc:'Ratatouille stammt aus der Provence und verbindet typische mediterrane Gemüse wie Aubergine, Zucchini, Paprika und Tomaten. Traditionell werden die Gemüse sorgfältig geschmort und mit Olivenöl sowie Kräutern aromatisiert.',ingredients:['350 g Aubergine','350 g Zucchini','350 g rote und/oder grüne Paprika','350 g Zwiebeln','500 g reife Tomaten','3 Knoblauchzehen','5–6 EL Olivenöl','2 Zweige Thymian','1 Lorbeerblatt','Salz','frisch gemahlener Pfeffer'],steps:['Aubergine und Zucchini in etwa 2 cm große Stücke schneiden. Paprika würfeln, Zwiebeln in Streifen schneiden, Tomaten grob würfeln und Knoblauch hacken.','Aubergine separat kräftig anbraten und herausnehmen. Anschließend Zucchini und Paprika ebenfalls nacheinander separat anbraten.','Zwiebeln langsam in Olivenöl weich werden lassen, Knoblauch kurz hinzufügen und anschließend Tomaten, Thymian und Lorbeer dazugeben.','Die Tomatenmischung etwa 10 Minuten einkochen lassen. Dann das angebratene Gemüse wieder hinzufügen und weitere 20–30 Minuten schmoren.','Mit Salz und Pfeffer abschmecken.']},
  'irish-stew':{title:'Irish Stew',subtitle:'Traditioneller Lammeintopf',portions:'6 Portionen',time:'ca. 90 Minuten',typeKey:'medium',desc:'Irish Stew gehört zu den bekanntesten traditionellen Gerichten Irlands und wurde ursprünglich aus wenigen, sättigenden Zutaten zubereitet. Lamm, Kartoffeln, Zwiebeln und Wurzelgemüse werden langsam gegart, bis ein kräftiger und dennoch einfacher Eintopf entsteht.',ingredients:['900 g Lammfleisch zum Schmoren','1 kg Kartoffeln','5–6 große Karotten','2–3 große Zwiebeln','1–1,2 l Lammfond','2–3 Zweige Thymian','1 Lorbeerblatt','Salz','schwarzer Pfeffer','Petersilie','Schnittlauch'],steps:['Lamm in große Würfel schneiden. Kartoffeln schälen und grob schneiden, Karotten und Zwiebeln vorbereiten.','Lamm mit dem Fond langsam zum Kochen bringen, den entstehenden Schaum abschöpfen und 10–15 Minuten sanft köcheln lassen.','Zwiebeln, Karotten, die Hälfte der Kartoffeln, Thymian und Lorbeer hinzufügen und etwa 30 Minuten köcheln lassen.','Restliche Kartoffeln hinzufügen und weitere 20–30 Minuten garen, bis Fleisch und Gemüse weich sind.','Den Eintopf etwa 15 Minuten ruhen lassen, abschmecken und mit Petersilie und Schnittlauch servieren.']},
  'poffertjes':{title:'Poffertjes',subtitle:'Kleine niederländische Pfannküchlein',portions:'ca. 4 Portionen',time:'etwa 75 Minuten inklusive Gehzeit',typeKey:'easy',desc:'Poffertjes sind kleine niederländische Pfannküchlein, die traditionell in einer speziellen Pfanne mit runden Vertiefungen gebacken werden. Typisch sind Hefeteig, Buchweizenanteil und das Servieren mit Butter und reichlich Puderzucker.',ingredients:['125 g Buchweizenmehl','125 g Weizenmehl Type 405','1 Päckchen Trockenhefe','2 EL Puderzucker','1 Prise Salz','1 Ei','30 g Butter','ca. 370 ml lauwarme Vollmilch','Butter für die Pfanne','Puderzucker'],steps:['Mehl, Hefe, Zucker und Salz vermengen. Ei und geschmolzene Butter hinzufügen.','Milch nach und nach einrühren und alles zu einem glatten, relativ flüssigen Hefeteig verrühren.','Den Teig etwa eine Stunde gehen lassen.','Poffertjes-Pfanne einfetten, die Vertiefungen zu etwa zwei Dritteln füllen und backen. Sobald sich sichtbare Bläschen bilden, wenden und die zweite Seite goldbraun backen.','Mit Butter und reichlich Puderzucker servieren.']},
  'bacalhau-a-bras':{title:'Bacalhau à Brás',subtitle:'Stockfisch mit Kartoffelstiften und Ei',portions:'4 Portionen',time:'Bacalhau 24–48 Stunden vorbereiten',typeKey:'medium',desc:'Bacalhau bezeichnet den in Portugal äußerst beliebten gesalzenen und getrockneten Kabeljau. Bacalhau à Brás ist ein Klassiker aus Lissabon und kombiniert den Fisch mit feinen Kartoffelstiften, Zwiebeln, cremigem Ei, Petersilie und schwarzen Oliven.',ingredients:['400–450 g eingesalzener Bacalhau','500–600 g Kartoffeln','1–2 große Zwiebeln','2 Knoblauchzehen','5–6 Eier','4–5 EL Olivenöl','Öl zum Ausbacken','glatte Petersilie','schwarze Oliven','Pfeffer','wenig Salz'],prep:'Bacalhau 24–48 Stunden in kaltem Wasser einweichen. Wasser mehrfach wechseln.',steps:['Kartoffeln in feine Streichholzstifte und Zwiebeln in dünne Scheiben schneiden. Bacalhau häuten, entgräten und zupfen. Eier leicht verschlagen.','Kartoffelstifte knusprig ausbacken und anschließend gut abtropfen lassen.','Zwiebeln langsam in Olivenöl weich garen, Knoblauch hinzufügen und den Bacalhau 2–3 Minuten mitgaren.','Die Kartoffeln unterheben und die Hitze reduzieren. Eier hinzufügen und nur so lange garen, bis die Mischung cremig ist.','Vom Herd nehmen, Petersilie unterheben und mit schwarzen Oliven servieren.']},
  'tortilla-de-patatas':{title:'Tortilla de Patatas',subtitle:'Spanisches Kartoffel-Omelett',portions:'4 Portionen',time:'ca. 45 Minuten',typeKey:'medium',desc:'Die Tortilla de Patatas gehört zu den bekanntesten Gerichten Spaniens und besteht im Kern aus Kartoffeln, Eiern, Olivenöl und – je nach persönlicher Überzeugung – Zwiebeln. Sie wird warm, lauwarm oder kalt gegessen und ist sowohl als Hauptgericht als auch als Tapa verbreitet.',ingredients:['500–600 g Kartoffeln','5–6 Eier','1 mittelgroße Zwiebel','etwa 250 ml Olivenöl','Salz'],steps:['Kartoffeln schälen und dünn schneiden. Zwiebel ebenfalls in dünne Scheiben schneiden.','Olivenöl erwärmen und die Kartoffeln darin langsam weich garen. Zwiebel hinzufügen, insgesamt etwa 15–20 Minuten garen und anschließend gut abtropfen lassen.','Eier aufschlagen, salzen und Kartoffeln sowie Zwiebeln unterheben. Die Mischung 10–15 Minuten ruhen lassen.','Die Mischung in die Pfanne geben und 4–6 Minuten garen.','Mit Hilfe eines Tellers wenden, zurück in die Pfanne gleiten lassen und die zweite Seite weitere 3–5 Minuten garen.']}
 },
 EN:{
  'lohikeitto':{title:'Lohikeitto',subtitle:'Finnish salmon soup',portions:'4 servings',time:'approx. 40 minutes',typeKey:'easy',desc:'Lohikeitto is a traditional Finnish salmon soup with potatoes, leek, cream and dill. The combination of creamy broth, mild salmon and fresh dill is especially characteristic of Nordic cuisine.',ingredients:['400 g skinless salmon fillet','600 g waxy potatoes','200 g carrots','1 large leek','1 tbsp butter','700 ml fish stock or mild fish broth','200 ml cream','1 bay leaf','3 allspice berries','½ bunch fresh dill','1–2 tbsp lemon juice','salt','black or white pepper'],steps:['Peel the potatoes and cut them into roughly 2 cm cubes. Slice the carrots and washed leek, check the salmon for bones and cut it into roughly 2–3 cm cubes.','Melt the butter in a large pot over medium heat. Gently sweat the leek for 3–4 minutes, then add the potatoes and carrots and sauté briefly.','Add the fish stock, bay leaf and allspice. Bring to the boil and simmer for 12–15 minutes until the potatoes are almost tender.','Stir in the cream, carefully add the salmon cubes and gently poach for 4–6 minutes. Do not boil vigorously.','Remove the bay leaf and allspice. Stir in chopped dill and lemon juice, then season with salt and pepper.'],serve:'Serve very hot and sprinkle with fresh dill. Dark rye bread goes especially well with it.'},
  'ratatouille':{title:'Ratatouille',subtitle:'Provençal vegetable stew',portions:'4 servings',time:'approx. 60–75 minutes',typeKey:'naturalVegan',desc:'Ratatouille comes from Provence and combines typical Mediterranean vegetables such as aubergine, courgette, peppers and tomatoes. Traditionally, the vegetables are carefully stewed and flavoured with olive oil and herbs.',ingredients:['350 g aubergine','350 g courgette','350 g red and/or green peppers','350 g onions','500 g ripe tomatoes','3 garlic cloves','5–6 tbsp olive oil','2 sprigs thyme','1 bay leaf','salt','freshly ground pepper'],steps:['Cut the aubergine and courgette into roughly 2 cm pieces. Dice the peppers and tomatoes, cut the onions into strips and chop the garlic.','Brown the aubergine separately over high heat and remove it. Then brown the courgette and peppers separately in turn.','Slowly soften the onions in olive oil, briefly add the garlic, then add the tomatoes, thyme and bay leaf.','Let the tomato mixture reduce for about 10 minutes. Return the browned vegetables and stew for another 20–30 minutes.','Season with salt and pepper.']},
  'irish-stew':{title:'Irish Stew',subtitle:'Traditional lamb stew',portions:'6 servings',time:'approx. 90 minutes',typeKey:'medium',desc:'Irish Stew is one of Ireland’s best-known traditional dishes and was originally prepared from only a few filling ingredients. Lamb, potatoes, onions and root vegetables are cooked slowly until the result is hearty yet simple.',ingredients:['900 g stewing lamb','1 kg potatoes','5–6 large carrots','2–3 large onions','1–1.2 l lamb stock','2–3 sprigs thyme','1 bay leaf','salt','black pepper','parsley','chives'],steps:['Cut the lamb into large cubes. Peel and roughly cut the potatoes, then prepare the carrots and onions.','Bring the lamb and stock slowly to the boil, skim off any foam and simmer gently for 10–15 minutes.','Add the onions, carrots, half of the potatoes, thyme and bay leaf and simmer for about 30 minutes.','Add the remaining potatoes and cook for another 20–30 minutes until the meat and vegetables are tender.','Leave the stew to rest for about 15 minutes, adjust the seasoning and serve with parsley and chives.']},
  'poffertjes':{title:'Poffertjes',subtitle:'Small Dutch pancakes',portions:'about 4 servings',time:'about 75 minutes including rising time',typeKey:'easy',desc:'Poffertjes are small Dutch pancakes traditionally baked in a special pan with round indentations. Yeast batter, a portion of buckwheat flour and serving them with butter and plenty of icing sugar are typical.',ingredients:['125 g buckwheat flour','125 g plain wheat flour','1 packet dry yeast','2 tbsp icing sugar','1 pinch salt','1 egg','30 g butter','approx. 370 ml lukewarm whole milk','butter for the pan','icing sugar'],steps:['Mix the flours, yeast, sugar and salt. Add the egg and melted butter.','Gradually stir in the milk until you have a smooth, relatively fluid yeast batter.','Leave the batter to rise for about one hour.','Grease the poffertjes pan, fill each hollow about two-thirds full and bake. Turn when visible bubbles appear and cook the second side until golden.','Serve with butter and plenty of icing sugar.']},
  'bacalhau-a-bras':{title:'Bacalhau à Brás',subtitle:'Salt cod with potato sticks and egg',portions:'4 servings',time:'prepare the bacalhau 24–48 hours in advance',typeKey:'medium',desc:'Bacalhau is the salted and dried cod that is extremely popular in Portugal. Bacalhau à Brás is a Lisbon classic combining the fish with fine potato sticks, onions, creamy egg, parsley and black olives.',ingredients:['400–450 g salted bacalhau','500–600 g potatoes','1–2 large onions','2 garlic cloves','5–6 eggs','4–5 tbsp olive oil','oil for frying','flat-leaf parsley','black olives','pepper','a little salt'],prep:'Soak the bacalhau in cold water for 24–48 hours. Change the water several times.',steps:['Cut the potatoes into fine matchsticks and thinly slice the onions. Skin, bone and flake the bacalhau, then lightly beat the eggs.','Fry the potato sticks until crisp and drain them well.','Slowly soften the onions in olive oil, add the garlic and cook the bacalhau for 2–3 minutes.','Fold in the potatoes and reduce the heat. Add the eggs and cook only until the mixture is creamy.','Remove from the heat, fold in the parsley and serve with black olives.']},
  'tortilla-de-patatas':{title:'Tortilla de Patatas',subtitle:'Spanish potato omelette',portions:'4 servings',time:'approx. 45 minutes',typeKey:'medium',desc:'Tortilla de Patatas is one of Spain’s best-known dishes and is essentially made from potatoes, eggs, olive oil and – depending on personal conviction – onions. It is eaten hot, warm or cold and is popular both as a main dish and as a tapa.',ingredients:['500–600 g potatoes','5–6 eggs','1 medium onion','about 250 ml olive oil','salt'],steps:['Peel the potatoes and slice them thinly. Thinly slice the onion as well.','Heat the olive oil and slowly cook the potatoes until tender. Add the onion, cook for about 15–20 minutes in total, then drain well.','Beat the eggs with salt, fold in the potatoes and onion and leave the mixture to rest for 10–15 minutes.','Pour the mixture into the pan and cook for 4–6 minutes.','Turn with the help of a plate, slide it back into the pan and cook the second side for another 3–5 minutes.']}
 },
 PT:{
  'lohikeitto':{title:'Lohikeitto',subtitle:'Sopa finlandesa de salmão',portions:'4 porções',time:'aprox. 40 minutos',typeKey:'easy',desc:'Lohikeitto é uma sopa tradicional finlandesa de salmão com batatas, alho-francês, natas e endro. A combinação do caldo cremoso, do salmão suave e do endro fresco é especialmente característica da cozinha nórdica.',ingredients:['400 g de filete de salmão sem pele','600 g de batatas de polpa firme','200 g de cenouras','1 alho-francês grande','1 c. de sopa de manteiga','700 ml de caldo de peixe suave','200 ml de natas','1 folha de louro','3 bagas de pimenta-da-jamaica','½ molho de endro fresco','1–2 c. de sopa de sumo de limão','sal','pimenta preta ou branca'],steps:['Descascar as batatas e cortá-las em cubos de cerca de 2 cm. Cortar as cenouras e o alho-francês, verificar se o salmão tem espinhas e cortá-lo em cubos de cerca de 2–3 cm.','Derreter a manteiga numa panela grande em lume médio. Refogar suavemente o alho-francês durante 3–4 minutos, juntar as batatas e as cenouras e refogar brevemente.','Adicionar o caldo de peixe, o louro e a pimenta-da-jamaica. Levantar fervura e cozinhar durante 12–15 minutos, até as batatas estarem quase macias.','Incorporar as natas, juntar cuidadosamente o salmão e deixar cozinhar suavemente durante 4–6 minutos. Não deixar ferver com força.','Retirar o louro e a pimenta-da-jamaica. Juntar o endro picado e o sumo de limão e temperar com sal e pimenta.'],serve:'Servir bem quente e polvilhar com endro fresco. Pão de centeio escuro acompanha especialmente bem.'},
  'ratatouille':{title:'Ratatouille',subtitle:'Prato provençal de legumes',portions:'4 porções',time:'aprox. 60–75 minutos',typeKey:'naturalVegan',desc:'A ratatouille vem da Provença e combina legumes mediterrânicos típicos como beringela, curgete, pimentos e tomate. Tradicionalmente, os legumes são estufados cuidadosamente e aromatizados com azeite e ervas.',ingredients:['350 g de beringela','350 g de curgete','350 g de pimento vermelho e/ou verde','350 g de cebola','500 g de tomates maduros','3 dentes de alho','5–6 c. de sopa de azeite','2 raminhos de tomilho','1 folha de louro','sal','pimenta moída na hora'],steps:['Cortar a beringela e a curgete em pedaços de cerca de 2 cm. Cortar os pimentos e tomates em cubos, as cebolas em tiras e picar o alho.','Alourar a beringela separadamente em lume forte e retirar. Depois alourar também, separadamente, a curgete e os pimentos.','Amolecer lentamente a cebola em azeite, juntar o alho por breves instantes e depois adicionar o tomate, o tomilho e o louro.','Deixar a mistura de tomate reduzir durante cerca de 10 minutos. Voltar a juntar os legumes alourados e estufar durante mais 20–30 minutos.','Temperar com sal e pimenta.']},
  'irish-stew':{title:'Irish Stew',subtitle:'Ensopado tradicional de borrego',portions:'6 porções',time:'aprox. 90 minutos',typeKey:'medium',desc:'O Irish Stew é um dos pratos tradicionais mais conhecidos da Irlanda e era originalmente preparado com poucos ingredientes, mas muito saciantes. Borrego, batatas, cebola e legumes de raiz cozinham lentamente até formar um ensopado substancial e simples.',ingredients:['900 g de borrego para estufar','1 kg de batatas','5–6 cenouras grandes','2–3 cebolas grandes','1–1,2 l de caldo de borrego','2–3 raminhos de tomilho','1 folha de louro','sal','pimenta preta','salsa','cebolinho'],steps:['Cortar o borrego em cubos grandes. Descascar e cortar grosseiramente as batatas e preparar as cenouras e as cebolas.','Levar lentamente o borrego e o caldo à fervura, retirar a espuma da superfície e cozinhar suavemente durante 10–15 minutos.','Juntar as cebolas, as cenouras, metade das batatas, o tomilho e o louro e cozinhar durante cerca de 30 minutos.','Juntar as restantes batatas e cozinhar por mais 20–30 minutos, até a carne e os legumes estarem macios.','Deixar o ensopado repousar durante cerca de 15 minutos, retificar os temperos e servir com salsa e cebolinho.']},
  'poffertjes':{title:'Poffertjes',subtitle:'Pequenas panquecas neerlandesas',portions:'cerca de 4 porções',time:'cerca de 75 minutos incluindo o tempo de levedação',typeKey:'easy',desc:'Os poffertjes são pequenas panquecas neerlandesas tradicionalmente preparadas numa frigideira especial com cavidades redondas. São típicos a massa levedada, a presença de farinha de trigo-sarraceno e o serviço com manteiga e bastante açúcar em pó.',ingredients:['125 g de farinha de trigo-sarraceno','125 g de farinha de trigo','1 saqueta de fermento de padeiro seco','2 c. de sopa de açúcar em pó','1 pitada de sal','1 ovo','30 g de manteiga','aprox. 370 ml de leite inteiro morno','manteiga para a frigideira','açúcar em pó'],steps:['Misturar as farinhas, o fermento, o açúcar e o sal. Juntar o ovo e a manteiga derretida.','Adicionar o leite gradualmente e mexer até obter uma massa levedada lisa e relativamente líquida.','Deixar a massa levedar durante cerca de uma hora.','Untar a frigideira de poffertjes, encher as cavidades até cerca de dois terços e cozinhar. Virar quando aparecerem bolhas visíveis e dourar o segundo lado.','Servir com manteiga e bastante açúcar em pó.']},
  'bacalhau-a-bras':{title:'Bacalhau à Brás',subtitle:'Bacalhau com batata-palha e ovo',portions:'4 porções',time:'preparar o bacalhau com 24–48 horas de antecedência',typeKey:'medium',desc:'Bacalhau é o peixe salgado e seco extremamente popular em Portugal. O Bacalhau à Brás é um clássico lisboeta que combina o peixe com batata-palha fina, cebola, ovo cremoso, salsa e azeitonas pretas.',ingredients:['400–450 g de bacalhau salgado','500–600 g de batatas','1–2 cebolas grandes','2 dentes de alho','5–6 ovos','4–5 c. de sopa de azeite','óleo para fritar','salsa de folha lisa','azeitonas pretas','pimenta','pouco sal'],prep:'Demolhar o bacalhau em água fria durante 24–48 horas. Mudar a água várias vezes.',steps:['Cortar as batatas em palitos muito finos e as cebolas em fatias finas. Retirar a pele e as espinhas do bacalhau, lascá-lo e bater ligeiramente os ovos.','Fritar os palitos de batata até ficarem estaladiços e escorrer bem.','Amolecer lentamente a cebola em azeite, juntar o alho e cozinhar o bacalhau durante 2–3 minutos.','Envolver as batatas e baixar o lume. Juntar os ovos e cozinhar apenas até obter uma consistência cremosa.','Retirar do lume, juntar a salsa e servir com azeitonas pretas.']},
  'tortilla-de-patatas':{title:'Tortilla de Patatas',subtitle:'Tortilha espanhola de batata',portions:'4 porções',time:'aprox. 45 minutos',typeKey:'medium',desc:'A Tortilla de Patatas é um dos pratos mais conhecidos de Espanha e é feita essencialmente com batatas, ovos, azeite e – dependendo da preferência pessoal – cebola. Come-se quente, morna ou fria e é popular tanto como prato principal como tapa.',ingredients:['500–600 g de batatas','5–6 ovos','1 cebola média','cerca de 250 ml de azeite','sal'],steps:['Descascar as batatas e cortá-las em rodelas finas. Cortar também a cebola em fatias finas.','Aquecer o azeite e cozinhar lentamente as batatas até ficarem macias. Juntar a cebola, cozinhar durante cerca de 15–20 minutos no total e escorrer bem.','Bater os ovos com sal, envolver as batatas e a cebola e deixar a mistura repousar durante 10–15 minutos.','Colocar a mistura na frigideira e cozinhar durante 4–6 minutos.','Virar com a ajuda de um prato, deslizar novamente para a frigideira e cozinhar o segundo lado durante mais 3–5 minutos.']}
 }
};

const VEGAN_INGREDIENTS = {
 DE:{
  'lohikeitto':['400 g fester Tofu oder vegane Fischalternative','600 g festkochende Kartoffeln','200 g Karotten','1 großer Lauch','1 EL vegane Butter','700 ml Gemüsefond','200 ml pflanzliche Kochcreme','1 Lorbeerblatt','3 Pimentkörner','½ Bund frischer Dill','1–2 EL Zitronensaft','Salz','Pfeffer'],
  'irish-stew':['500 g Kräuterseitlinge oder vegane Fleischalternative','1 kg Kartoffeln','5–6 große Karotten','2–3 große Zwiebeln','1–1,2 l kräftige Gemüsebrühe','2–3 Zweige Thymian','1 Lorbeerblatt','Salz','schwarzer Pfeffer','Petersilie','Schnittlauch'],
  'poffertjes':['125 g Buchweizenmehl','125 g Weizenmehl Type 405','1 Päckchen Trockenhefe','2 EL Puderzucker','1 Prise Salz','1 EL Apfelmus','30 g vegane Butter','ca. 370 ml Pflanzenmilch','vegane Butter für die Pfanne','Puderzucker'],
  'bacalhau-a-bras':['400 g marinierter Tofu oder vegane Fischalternative','500–600 g Kartoffeln','1–2 große Zwiebeln','2 Knoblauchzehen','250 g Seidentofu','4–5 EL Olivenöl','Öl zum Ausbacken','glatte Petersilie','schwarze Oliven','Pfeffer','wenig Salz'],
  'tortilla-de-patatas':['500–600 g Kartoffeln','250 g Kichererbsenmehl','350 ml Wasser','1 mittelgroße Zwiebel','etwa 250 ml Olivenöl','Salz']
 },
 EN:{
  'lohikeitto':['400 g firm tofu or vegan fish alternative','600 g waxy potatoes','200 g carrots','1 large leek','1 tbsp vegan butter','700 ml vegetable stock','200 ml plant-based cooking cream','1 bay leaf','3 allspice berries','½ bunch fresh dill','1–2 tbsp lemon juice','salt','pepper'],
  'irish-stew':['500 g king oyster mushrooms or vegan meat alternative','1 kg potatoes','5–6 large carrots','2–3 large onions','1–1.2 l strong vegetable stock','2–3 sprigs thyme','1 bay leaf','salt','black pepper','parsley','chives'],
  'poffertjes':['125 g buckwheat flour','125 g plain wheat flour','1 packet dry yeast','2 tbsp icing sugar','1 pinch salt','1 tbsp apple sauce','30 g vegan butter','approx. 370 ml plant milk','vegan butter for the pan','icing sugar'],
  'bacalhau-a-bras':['400 g marinated tofu or vegan fish alternative','500–600 g potatoes','1–2 large onions','2 garlic cloves','250 g silken tofu','4–5 tbsp olive oil','oil for frying','flat-leaf parsley','black olives','pepper','a little salt'],
  'tortilla-de-patatas':['500–600 g potatoes','250 g chickpea flour','350 ml water','1 medium onion','about 250 ml olive oil','salt']
 },
 PT:{
  'lohikeitto':['400 g de tofu firme ou alternativa vegana a peixe','600 g de batatas de polpa firme','200 g de cenouras','1 alho-francês grande','1 c. de sopa de manteiga vegana','700 ml de caldo de legumes','200 ml de creme vegetal para cozinhar','1 folha de louro','3 bagas de pimenta-da-jamaica','½ molho de endro fresco','1–2 c. de sopa de sumo de limão','sal','pimenta'],
  'irish-stew':['500 g de cogumelos eryngii ou alternativa vegana a carne','1 kg de batatas','5–6 cenouras grandes','2–3 cebolas grandes','1–1,2 l de caldo de legumes forte','2–3 raminhos de tomilho','1 folha de louro','sal','pimenta preta','salsa','cebolinho'],
  'poffertjes':['125 g de farinha de trigo-sarraceno','125 g de farinha de trigo','1 saqueta de fermento de padeiro seco','2 c. de sopa de açúcar em pó','1 pitada de sal','1 c. de sopa de puré de maçã','30 g de manteiga vegana','aprox. 370 ml de bebida vegetal','manteiga vegana para a frigideira','açúcar em pó'],
  'bacalhau-a-bras':['400 g de tofu marinado ou alternativa vegana a peixe','500–600 g de batatas','1–2 cebolas grandes','2 dentes de alho','250 g de tofu sedoso','4–5 c. de sopa de azeite','óleo para fritar','salsa de folha lisa','azeitonas pretas','pimenta','pouco sal'],
  'tortilla-de-patatas':['500–600 g de batatas','250 g de farinha de grão-de-bico','350 ml de água','1 cebola média','cerca de 250 ml de azeite','sal']
 }
};

function getCountryName(c,lang){return COUNTRY_NAMES[lang]?.[c.code] || COUNTRY_NAMES.DE[c.code]}
function getRecipe(slug,lang){return RECIPES[lang]?.[slug] || RECIPES.DE[slug]}
function getTypeLabel(typeKey,t){return typeKey==='naturalVegan'?t.naturalType:typeKey==='medium'?t.medium:t.easy}

function usePath(){
 const [path,setPath] = useState(location.pathname);
 useEffect(()=>{ const f=()=>setPath(location.pathname); addEventListener('popstate',f); return()=>removeEventListener('popstate',f)},[]);
 const go=(to)=>{ history.pushState({},'',to); setPath(to); window.scrollTo({top:0,behavior:'smooth'}); };
 return [path,go];
}

const ease = [0.22,1,0.36,1];
function ScrollPlop({as='div', children, className='', style, start='start 94%', end='start 72%', ...props}){
 const ref=useRef(null); const reduceMotion=useReducedMotion();
 const {scrollYProgress}=useScroll({target:ref,offset:[start,end]});
 const progress=useSpring(scrollYProgress,{stiffness:260,damping:30,mass:.38,restDelta:.001});
 const opacity=useTransform(progress,[0,.82,1],[0,.9,1]); const y=useTransform(progress,[0,1],[28,0]); const scale=useTransform(progress,[0,1],[.935,1]); const filter=useTransform(progress,[0,1],['blur(10px)','blur(0px)']);
 const Tag=as==='button'?motion.button:as==='article'?motion.article:as==='section'?motion.section:motion.div;
 const motionStyle=reduceMotion?{opacity:1,y:0,scale:1,filter:'blur(0px)'}:{opacity,y,scale,filter};
 return <Tag ref={ref} className={className} style={{...style,...motionStyle}} {...props}>{children}</Tag>;
}

function CursorGlow(){
 const ref=useRef();
 useEffect(()=>{const m=e=>{if(ref.current) ref.current.style.transform=`translate3d(${e.clientX-160}px,${e.clientY-160}px,0)`}; addEventListener('pointermove',m); return()=>removeEventListener('pointermove',m)},[]);
 return <div ref={ref} className="cursor-glow"/>;
}

function Header({go,lang,setLang,t}){
 const [open,setOpen]=useState(false); const languages=['DE','EN','PT'];
 const menuItems=[[t.home,'/'],[t.allRecipes,'/rezepte'],[t.aboutProject,'/#projekt']];
 return <>
  <motion.header className="header" initial={{y:-70,opacity:0}} animate={{y:0,opacity:1}} transition={{duration:.7,ease}}>
   <button className="brand" onClick={()=>go('/')}>Pictorius <span>×</span> {t.europe}</button>
   <div className="header-actions"><div className="lang" aria-label={t.languageAria}>{languages.map(code=><button key={code} className={lang===code?'active':''} onClick={()=>setLang(code)} aria-pressed={lang===code} title={code==='DE'?'Deutsch':code==='EN'?'English':'Português'}>{code}</button>)}</div><button className="menu-btn" onClick={()=>setOpen(true)}><span>{t.menu}</span><Menu size={18}/></button></div>
  </motion.header>
  <AnimatePresence>{open&&<motion.div className="menu-overlay" initial={{clipPath:'circle(0% at 95% 5%)'}} animate={{clipPath:'circle(150% at 95% 5%)'}} exit={{clipPath:'circle(0% at 95% 5%)'}} transition={{duration:.7,ease}}><button className="close" aria-label={t.closeMenu} onClick={()=>setOpen(false)}><X/></button><nav>{menuItems.map(([l,u],i)=><motion.button key={l} initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:.15+i*.08}} onClick={()=>{setOpen(false);if(u.includes('#')){go('/');setTimeout(()=>document.querySelector('#projekt')?.scrollIntoView({behavior:'smooth'}),80)}else go(u)}}><span>0{i+1}</span>{l}<ArrowDownRight/></motion.button>)}</nav></motion.div>}</AnimatePresence>
 </>;
}

function PlateScene({go,scrollY,lang,t}){
 const y=useTransform(scrollY,[0,850],[0,48]);
 return <motion.div className="plate-scene" style={{y}} initial={{scale:.9,opacity:0,filter:'blur(12px)'}} animate={{scale:1,opacity:1,filter:'blur(0px)'}} transition={{delay:.2,duration:1.05,ease}}>
  <div className="plate-halo"/><div className="orbit-stage"><div className="orbit-guide" aria-hidden="true"/><div className="orbit-ring">{countries.map((c,i)=>{const angle=i*60;const r=getRecipe(c.slug,lang);const name=getCountryName(c,lang);return <div key={c.code} className="orbit-slot" style={{'--angle':`${angle}deg`,'--counter-angle':`${-angle}deg`}}><div className="orbit-static-counter"><div className="orbit-motion-counter"><motion.button className="dish-orbit" onClick={()=>go('/rezepte/'+c.slug)} initial={{opacity:0,scale:.55}} animate={{opacity:1,scale:1}} whileHover={{scale:1.12}} whileTap={{scale:1.03}} transition={{opacity:{delay:.42+i*.07,duration:.42},scale:{delay:.42+i*.07,type:'spring',stiffness:270,damping:19}}} aria-label={`${name}: ${r.title}`}><img src={c.image} alt={`${r.title} – ${name}`}/><span className="dish-orbit-shine"/><span className="dish-orbit-label"><small>{name}</small><strong>{r.title}</strong><em>{c.code}</em></span></motion.button></div></div></div>})}</div></div>
  <div className="center-plate-anchor"><motion.button className="center-plate" onClick={()=>go('/rezepte')} whileHover={{scale:1.018}} whileTap={{scale:.99}} transition={{type:'spring',stiffness:240,damping:20}} aria-label={t.discoverRecipes}><span className="center-plate-ring"/><span className="plate-well"><strong>6×2</strong><small>{t.discoverRecipes}</small></span></motion.button></div>
 </motion.div>;
}

function RecipeRail({go,lang,t}){
 const rail=useRef(null); const drag=useRef({active:false,x:0,left:0}); const items=[...countries,...countries];
 const down=e=>{if(!rail.current)return;drag.current={active:true,x:e.clientX,left:rail.current.scrollLeft};rail.current.setPointerCapture?.(e.pointerId);rail.current.classList.add('dragging')};
 const move=e=>{if(!drag.current.active||!rail.current)return;rail.current.scrollLeft=drag.current.left-(e.clientX-drag.current.x)}; const up=e=>{drag.current.active=false;rail.current?.releasePointerCapture?.(e.pointerId);rail.current?.classList.remove('dragging')};
 return <ScrollPlop className="recipe-rail-shell" start="start 99%" end="start 86%"><div className="recipe-rail-label">{t.scrollDrag}</div><div ref={rail} className="recipe-rail" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}>{items.map((c,i)=>{const r=getRecipe(c.slug,lang);return <button key={`${c.code}-${i}`} onClick={()=>{if(Math.abs((rail.current?.scrollLeft||0)-drag.current.left)<6)go('/rezepte/'+c.slug)}}><strong>{r.title}</strong><span>– {getCountryName(c,lang)}</span><em>{c.code}</em></button>})}</div><div className="rail-fade rail-fade-left"/><div className="rail-fade rail-fade-right"/></ScrollPlop>;
}

function Hero({go,lang,t}){
 const {scrollY}=useScroll(); const y1=useTransform(scrollY,[0,800],[0,-140]); const y2=useTransform(scrollY,[0,800],[0,110]);
 return <section className="hero" id="top"><motion.div className="hero-orb orb-a" style={{y:y1}}/><motion.div className="hero-orb orb-b" style={{y:y2}}/><div className="hero-grid"><motion.div className="eyebrow" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:.18,duration:.6}}>Pictorius Berufskolleg · Erasmus+</motion.div><div className="hero-copy"><motion.h1 initial={{opacity:0,y:70,filter:'blur(12px)'}} animate={{opacity:1,y:0,filter:'blur(0px)'}} transition={{duration:1.05,ease}}><span>{t.europe}</span><br/>{t.heroPlate}</motion.h1><motion.p initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:.35,duration:.8,ease}}>{t.heroLead}<br/><small>{t.heroSub}</small></motion.p><motion.div className="hero-actions" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.55}}><button onClick={()=>document.querySelector('#countries')?.scrollIntoView({behavior:'smooth'})}>{t.discoverCountries} <ArrowDownRight/></button><button className="ghost" onClick={()=>document.querySelector('#recipes')?.scrollIntoView({behavior:'smooth'})}>{t.discoverRecipes}</button></motion.div></div><PlateScene go={go} scrollY={scrollY} lang={lang} t={t}/></div><RecipeRail go={go} lang={lang} t={t}/></section>;
}

function Countries({go,lang,t}){
 return <section className="section countries" id="countries">
  <ScrollPlop className="section-head" start="start 96%" end="start 77%"><div><span className="kicker">{t.countriesKicker}</span><h2>{t.chooseCountry}</h2></div><p>{t.countriesDesc}</p></ScrollPlop>
  <div className="country-grid">{countries.map((c,i)=><ScrollPlop as="button" key={c.code} className="country-card" style={{'--card':c.color,'--accent':c.accent}} onClick={()=>go('/rezepte/'+c.slug)} start="start 96%" end={`start ${76-i*1.2}%`} whileHover={{y:-8,scale:1.012}} whileTap={{scale:.99}}><div className="country-top"><span>{c.n}</span><span>{c.lat}</span></div><div className="country-visual"><div className="country-disc">{c.code}</div></div><div className="country-bottom"><div><small>{c.local}</small><strong>{getCountryName(c,lang)}</strong></div><span className="open-dot"><ArrowDownRight/></span></div></ScrollPlop>)}</div>
 </section>;
}

function RecipeCard({c,go,index,lang,t}){
 const r=getRecipe(c.slug,lang); const name=getCountryName(c,lang);
 return <ScrollPlop as="article" className="recipe-card" start="start 96%" end={`start ${75-Math.min(index,5)*1.1}%`} onClick={()=>go('/rezepte/'+c.slug)} whileHover={{scale:1.006}}><div className="rc-meta"><span>{c.n} · {c.code} · {c.lat}</span>{c.category==='natural-vegan'&&<span className="badge">{t.naturalVegan}</span>}</div><div className="rc-content"><div><small>{name}</small><h3>{r.title}</h3><p>{r.desc}</p></div><div className="rc-image"><img src={c.image} alt={`${r.title} – ${name}`}/><span><ArrowDownRight/></span></div></div><div className="rc-foot"><span>{r.time}</span><span>{r.portions}</span><strong>{t.openRecipe} <ArrowRight size={16}/></strong></div></ScrollPlop>;
}

function RecipesSection({go,lang,t,standalone=false}){
 const [filter,setFilter]=useState('all'); const filtered=useMemo(()=>countries.filter(c=>filter==='all'||(filter==='vegan'&&c.slug!=='ratatouille')||c.category===filter),[filter]);
 const filters=[['all',t.filterAll],['vegan',t.filterVegan],['natural-vegan',t.filterNatural],['vegetarian',t.filterVegetarian],['fish',t.filterFish],['meat',t.filterMeat]];
 return <section className={'section recipes '+(standalone?'standalone':'')} id="recipes">
  <ScrollPlop className="section-head recipes-head" start="start 96%" end="start 78%"><div><span className="kicker">{t.recipesKicker}</span><h2>{t.allDishes}</h2></div><div className="counter"><span>{String(filtered.length).padStart(2,'0')}</span><small>{t.dishes}</small></div></ScrollPlop>
  <ScrollPlop className="filters" start="start 96%" end="start 81%">{filters.map(([k,l])=><button key={k} onClick={()=>setFilter(k)} className={filter===k?'active':''}>{l}</button>)}</ScrollPlop>
  <AnimatePresence mode="popLayout"><motion.div layout className="recipe-list">{filtered.map((c,i)=><RecipeCard c={c} go={go} index={i} lang={lang} t={t} key={c.code}/>)}</motion.div></AnimatePresence>
 </section>;
}

function Project({t}){
 const steps=[['01',t.stepWood,t.stepWoodSub],['02',t.stepQr,t.stepQrSub],['03',t.stepRecipe,t.stepRecipeSub]];
 return <section className="project" id="projekt">
  <ScrollPlop className="project-img" start="start 96%" end="start 73%"><img src="https://images.unsplash.com/photo-1456406644174-8ddd4cd52a06?auto=format&fit=crop&w=1600&q=80" alt={t.projectImage}/></ScrollPlop>
  <div className="project-copy"><ScrollPlop start="start 95%" end="start 76%"><span className="kicker">{t.projectKicker}</span><h2>{t.projectTitle}</h2><p>{t.projectDesc}</p></ScrollPlop><div className="steps-mini">{steps.map((x,i)=><ScrollPlop key={x[0]} start="start 96%" end={`start ${80-i*2}%`}><span>{x[0]}</span><strong>{x[1]}</strong><small>{x[2]}</small></ScrollPlop>)}</div></div>
 </section>;
}

function Stats({t}){return <section className="stats"><ScrollPlop start="start 96%" end="start 78%"><span className="kicker">Erasmus+</span><h2>{t.statsTitle}<br/>Pictorius Berufskolleg Coesfeld</h2></ScrollPlop><div className="stats-grid">{[['06',t.countries],['06',t.traditionalDishes],['06',t.veganInterpretations]].map((x,i)=><ScrollPlop key={x[1]} start="start 96%" end={`start ${79-i*2}%`}><strong>{x[0]}</strong><span>{x[1]}</span></ScrollPlop>)}</div></section>}

function Marquee({lang}){const names=COUNTRY_NAMES[lang];const line=`Hyvää ruokahalua! · ${names.FI}   Bon appétit ! · ${names.FR}   Bain taitneamh as! · ${names.IE}   Eet smakelijk! · ${names.NL}   Bom apetite! · ${names.PT}   ¡Buen provecho! · ${names.ES}   `;return <div className="marquee"><div>{line.repeat(3)}</div><div>{line.repeat(3)}</div></div>}

function Footer({go,t}){return <footer><div><h3>European Recipes</h3><p>{t.footerProject}<br/>Pictorius Berufskolleg Coesfeld</p></div><nav><button onClick={()=>go('/')}>{t.home}</button><button onClick={()=>go('/rezepte')}>{t.allRecipes}</button><button onClick={()=>{go('/');setTimeout(()=>document.querySelector('#projekt')?.scrollIntoView({behavior:'smooth'}),100)}}>{t.aboutProject}</button></nav><button className="top" onClick={()=>scrollTo({top:0,behavior:'smooth'})}>{t.backToTop}</button><div className="copyright">© 2026 Pictorius Berufskolleg Coesfeld <span>Erasmus+ · European Recipes</span></div></footer>}

function Home({go,lang,t}){return <><Hero go={go} lang={lang} t={t}/><Countries go={go} lang={lang} t={t}/><RecipesSection go={go} lang={lang} t={t}/><Project t={t}/><Stats t={t}/><Marquee lang={lang}/><Footer go={go} t={t}/></>}

function VariantControl({vegan,setVegan,natural=false,onChange,t}){
 if(natural)return <div className="natural-vegan-pill"><span className="leaf-dot"/>{t.naturalVegan}</div>;
 const choose=value=>{setVegan(value);onChange?.()};
 return <div className="variant-block"><span className="variant-label">{t.recipeVariant}</span><div className="variant-control" role="group" aria-label={t.chooseVariant}><button className={!vegan?'active original-active':''} aria-pressed={!vegan} onClick={()=>choose(false)}>{t.original}</button><button className={vegan?'active vegan-active':''} aria-pressed={vegan} onClick={()=>choose(true)}><span className="leaf-dot"/>{t.vegan}</button></div></div>;
}

function RecipePage({slug,go,lang,t}){
 const r=getRecipe(slug,lang); const c=countries.find(x=>x.slug===slug); const natural=r?.typeKey==='naturalVegan'; const [vegan,setVegan]=useState(natural); const [checked,setChecked]=useState([]); const [done,setDone]=useState([]);
 useEffect(()=>{setVegan(natural);setChecked([]);setDone([])},[slug,natural]);
 useEffect(()=>{setChecked([]);setDone([])},[lang]);
 if(!r||!c)return <div className="notfound"><h1>404</h1><button onClick={()=>go('/')}>{t.back}</button></div>;
 const ingredients=vegan&&!natural&&VEGAN_INGREDIENTS[lang]?.[slug]?VEGAN_INGREDIENTS[lang][slug]:r.ingredients; const idx=countries.findIndex(x=>x.slug===slug); const prev=countries[idx-1],next=countries[idx+1]; const name=getCountryName(c,lang);
 const toggleCheck=i=>setChecked(s=>s.includes(i)?s.filter(x=>x!==i):[...s,i]); const toggleDone=i=>setDone(s=>s.includes(i)?s.filter(x=>x!==i):[...s,i]);
 return <main className={`recipe-page ${vegan?'vegan-mode':'original-mode'}`} style={{'--accent':c.accent,'--tint':c.color}}><div className="recipe-breadcrumb"><button onClick={()=>go('/')}>{t.europe}</button><span>/</span><span>{name}</span><span>/</span><strong>{r.title}</strong></div><section className="recipe-hero"><motion.div className="recipe-title" initial={{opacity:0,y:45,filter:'blur(12px)'}} animate={{opacity:1,y:0,filter:'blur(0)'}} transition={{duration:.9,ease}}><span className="recipe-meta">{c.n} · {c.code} · {c.lat} · {name}</span><h1>{r.title}</h1><h2>{r.subtitle}</h2><p>{r.desc}</p><VariantControl vegan={vegan} setVegan={setVegan} natural={natural} onChange={()=>setChecked([])} t={t}/><div className="recipe-info"><div><small>{t.portions}</small><strong>{r.portions}</strong></div><div><small>{t.time}</small><strong>{r.time}</strong></div><div><small>{t.type}</small><strong>{vegan&&!natural?t.veganVariant:getTypeLabel(r.typeKey,t)}</strong></div></div></motion.div><motion.div className="recipe-image" initial={{opacity:0,scale:.94}} animate={{opacity:1,scale:1}} transition={{duration:1,ease}}><img src={c.image} alt={`${r.title} – ${name}`}/>{vegan&&<motion.span className="vegan-image-tag" initial={{opacity:0,scale:.8}} animate={{opacity:1,scale:1}}><i className="leaf-dot"/>{t.vegan}</motion.span>}</motion.div></section>
 <section className="cook-grid"><div className="ingredients"><ScrollPlop className="cook-head" start="start 93%" end="start 76%"><h2>{t.ingredients}</h2><span>{checked.length}/{ingredients.length} {t.ready}</span></ScrollPlop><ScrollPlop className="progress" start="start 93%" end="start 78%"><i style={{width:`${checked.length/ingredients.length*100}%`}}/></ScrollPlop><div className="plop-list">{ingredients.map((x,i)=><ScrollPlop as="button" className={checked.includes(i)?'checked':''} onClick={()=>toggleCheck(i)} key={`${lang}-${vegan?'v':'o'}-${i}`} whileHover={{x:7,scale:1.012}} whileTap={{scale:.985}} start="start 95%" end="start 74%"><span className="box">{checked.includes(i)&&<Check size={16}/>}</span><em>{x}</em></ScrollPlop>)}</div>{r.prep&&<ScrollPlop className="prep" start="start 94%" end="start 75%"><span>{t.prep}</span><p>{r.prep}</p></ScrollPlop>}</div>
 <div className="preparation"><ScrollPlop className="cook-head" start="start 93%" end="start 76%"><h2>{t.preparation}</h2><span>{done.length} {t.of} {r.steps.length} {t.stepsDone}</span></ScrollPlop><ScrollPlop className="progress" start="start 93%" end="start 78%"><i style={{width:`${done.length/r.steps.length*100}%`}}/></ScrollPlop><div className="plop-list steps-plop compact-steps">{r.steps.map((x,i)=><ScrollPlop className={'step '+(done.includes(i)?'done':'')} key={`${lang}-${i}`} whileHover={{x:5,scale:1.006}} start="start 95%" end="start 73%"><button className="step-compact" onClick={()=>toggleDone(i)} aria-pressed={done.includes(i)}><span className="step-number">{String(i+1).padStart(2,'0')}</span><p>{x}</p><span className="step-check">{done.includes(i)?<Check size={16}/>:<i/>}</span></button></ScrollPlop>)}</div>{r.serve&&<ScrollPlop className="serve" start="start 94%" end="start 75%"><span>{t.serve}</span><p>{r.serve}</p></ScrollPlop>}</div></section>
 <nav className="recipe-nav">{prev?<button onClick={()=>go('/rezepte/'+prev.slug)}><ArrowLeft/><span><small>{t.previousDish}</small>{getRecipe(prev.slug,lang).title}<em>{getCountryName(prev,lang)}</em></span></button>:<div/>}<button className="all" onClick={()=>go('/rezepte')}>{t.viewAllRecipes}</button>{next?<button onClick={()=>go('/rezepte/'+next.slug)}><span><small>{t.nextDish}</small>{getRecipe(next.slug,lang).title}<em>{getCountryName(next,lang)}</em></span><ArrowRight/></button>:<div/>}</nav><Footer go={go} t={t}/></main>;
}

function App(){
 const [path,go]=usePath();
 const [langState,setLangState]=useState(()=>{try{const saved=localStorage.getItem('euro-taste-lang');return ['DE','EN','PT'].includes(saved)?saved:'DE'}catch{return 'DE'}}); const lang=langState; const t=UI[lang];
 const setLang=code=>{setLangState(code);try{localStorage.setItem('euro-taste-lang',code)}catch{}};
 const {scrollYProgress}=useScroll(); const smooth=useSpring(scrollYProgress,{stiffness:120,damping:28,mass:.2});
 useEffect(()=>{document.documentElement.lang=lang==='DE'?'de':lang==='PT'?'pt':'en';document.title=lang==='DE'?'European Recipes · Erasmus+':lang==='EN'?'European Recipes · Erasmus+':'Receitas Europeias · Erasmus+'},[lang]);
 let page=path==='/rezepte'?<><div className="page-spacer"/><RecipesSection go={go} lang={lang} t={t} standalone/><Marquee lang={lang}/><Footer go={go} t={t}/></>:path.startsWith('/rezepte/')?<RecipePage slug={decodeURIComponent(path.split('/').pop())} go={go} lang={lang} t={t}/>:<Home go={go} lang={lang} t={t}/>;
 return <><motion.div className="scroll-progress" style={{scaleX:smooth}}/><CursorGlow/><Header go={go} lang={lang} setLang={setLang} t={t}/><AnimatePresence mode="wait"><motion.div key={`${path}-${lang}`} initial={{opacity:0,filter:'blur(5px)'}} animate={{opacity:1,filter:'blur(0)'}} exit={{opacity:0,filter:'blur(6px)'}} transition={{duration:.3,ease}}>{page}</motion.div></AnimatePresence></>;
}

createRoot(document.getElementById('root')).render(<App/>);
